postgres:
  container_name: postgres
  image: postgres:14.7-alpine
  environment:
    POSTGRES_USER: groovanoscode
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust
  ports:
    - "5432:5432"